/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AuthorActorId = string;
export type ActorId = string;
export type Name = string | null;
export type ProfilePhotoUrl = string | null;
export type Username = string | null;
export type Contents = string;
export type CreatedAt = string;
export type CreatedDurationSeconds = number;
export type TargetType = string;
export type TargetDatabase = string | null;
export type TargetTable = string | null;
export type TargetRowIds = string | null;
export type TargetColumn = string | null;
export type TargetLabel = string | null;
export type Data = ActivitySearchResult[];

export interface ActivitySearchResponse {
  data: Data;
  [k: string]: unknown;
}
export interface ActivitySearchResult {
  author_actor_id: AuthorActorId;
  author: Author;
  contents: Contents;
  created_at: CreatedAt;
  created_duration_seconds: CreatedDurationSeconds;
  target_type: TargetType;
  target_database?: TargetDatabase;
  target_table?: TargetTable;
  target_row_ids?: TargetRowIds;
  target_column?: TargetColumn;
  target_label?: TargetLabel;
  [k: string]: unknown;
}
export interface Author {
  actor_id: ActorId;
  name?: Name;
  profile_photo_url?: ProfilePhotoUrl;
  username?: Username;
  [k: string]: unknown;
}
