/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Username = string;
export type ActorId = string;
export type Name = string | null;
export type ProfilePhotoUrl = string | null;
export type Username1 = string | null;
export type Suggestions = MentionSuggestion[];

export interface AutocompleteMentionsResponse {
  suggestions: Suggestions;
  [k: string]: unknown;
}
export interface MentionSuggestion {
  username: Username;
  author: Author;
  [k: string]: unknown;
}
export interface Author {
  actor_id: ActorId;
  name?: Name;
  profile_photo_url?: ProfilePhotoUrl;
  username?: Username1;
  [k: string]: unknown;
}
