/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ThreadId = string;
export type Contents = string;

export interface CommentAddRequest {
  thread_id: ThreadId;
  contents: Contents;
  [k: string]: unknown;
}
