/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Id = string;
export type ActorId = string;
export type Name = string | null;
export type ProfilePhotoUrl = string | null;
export type Username = string | null;
export type Contents = string;
export type CreatedAt = string;
export type CreatedDurationSeconds = number;
export type NodeType = string;
export type Value = string;
export type RenderNodes = RenderNode[];
export type ReactorActorId = string;
export type Reaction = string;
export type Reactions = ReactionData[];

export interface CommentData {
  id: Id;
  author: Author;
  contents: Contents;
  created_at: CreatedAt;
  created_duration_seconds: CreatedDurationSeconds;
  render_nodes: RenderNodes;
  reactions: Reactions;
  [k: string]: unknown;
}
export interface Author {
  actor_id: ActorId;
  name?: Name;
  profile_photo_url?: ProfilePhotoUrl;
  username?: Username;
  [k: string]: unknown;
}
export interface RenderNode {
  node_type: NodeType;
  value: Value;
  [k: string]: unknown;
}
export interface ReactionData {
  reactor_actor_id: ReactorActorId;
  reaction: Reaction;
  [k: string]: unknown;
}
