/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Ok = boolean;
export type RowThreads = string[];

export interface RowViewThreadsResponse {
  ok: Ok;
  data: RowViewThreadsData;
  [k: string]: unknown;
}
export interface RowViewThreadsData {
  row_threads: RowThreads;
  [k: string]: unknown;
}
