/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Ok = boolean;
export type Id = string;
export type TableThreads = TableThreadItem[];
export type ColumnThreads = unknown[];
export type Id1 = string;
export type Rowids = string;
export type RowThreads = RowThreadItem[];
export type ValueThreads = unknown[];

export interface TableViewThreadsResponse {
  ok: Ok;
  data: TableViewThreadsData;
  [k: string]: unknown;
}
export interface TableViewThreadsData {
  table_threads: TableThreads;
  column_threads: ColumnThreads;
  row_threads: RowThreads;
  value_threads: ValueThreads;
  [k: string]: unknown;
}
export interface TableThreadItem {
  id: Id;
  [k: string]: unknown;
}
export interface RowThreadItem {
  id: Id1;
  rowids: Rowids;
  [k: string]: unknown;
}
