/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Type = string;
export type Database = string | null;
export type Table = string | null;
export type Column = string | null;
export type Rowids = string | null;
export type Comment = string;

export interface ThreadNewRequest {
  type: Type;
  database?: Database;
  table?: Table;
  column?: Column;
  rowids?: Rowids;
  comment: Comment;
  [k: string]: unknown;
}
